<?php

$this->headTitle('Simple Form');

$this->mainMenu()->setActiveItemId('simpleForm');

$this->pageBreadcrumbs()->setItems(array(
            'Home'=>$this->url('home'),
            'Simple Form'=>$this->url('simpleform')
            ));

?>

<h1>Error Sending Email!</h1>

<p>
    <div class="alert alert-warning">
        Sorry, but we had an unexpected problem when trying to deliver your message. 
        Please try again later.
    </div>
</p>
