<?php

$this->headTitle('Simple Form');

$this->mainMenu()->setActiveItemId('simpleForm');

$this->pageBreadcrumbs()->setItems(array(
            'Home'=>$this->url('home'),
            'Simple Form'=>$this->url('simpleform')
            ));

$form = $this->form;
$form->setAttribute('action', $this->url('simpleform'));
$form->get('firstName')->setAttributes(array(
    'class'=>'form-control',
    'placeholder'=>'Type your First Name here'
    ));
$form->get('lastName')->setAttributes(array(
    'class'=>'form-control',
    'placeholder'=>'Type your Last Name here'
    ));
$form->get('email')->setAttributes(array(
    'class'=>'form-control', 
    'placeholder'=>'name@example.com'
    ));

$form->get('submit')->setAttributes(array('class'=>'btn btn-primary'));
$form->prepare();

?>

<h1>Simple Form</h1>
<p>
    Please fill out the following form.
</p>

<div class="row">
    <div class="col-md-6">
        <?php echo $this->form()->openTag($form); ?>
        <div class="form-group">
            <?php echo $this->formLabel($form->get('firstName')); ?>
            <?php echo $this->formElement($form->get('firstName')); ?>
            <?php echo $this->formElementErrors($form->get('firstName')); ?>  
        </div> 
        
	<div class="form-group">
            <?php echo $this->formLabel($form->get('lastName')); ?>
            <?php echo $this->formElement($form->get('lastName')); ?>
            <?php echo $this->formElementErrors($form->get('lastName')); ?>
        </div>

	<div class="form-group">
            <?php echo $this->formLabel($form->get('email')); ?>
            <?php echo $this->formElement($form->get('email')); ?>
            <?php echo $this->formElementErrors($form->get('email')); ?>
        </div>

    	<div id="email-message" class="alert alert-danger" style="display: none">
    	</div>        
        
        <?php echo $this->formElement($form->get('csrf')); ?>
        
        <?php echo $this->formElement($form->get('submit')); ?>
        
        <?php echo $this->form()->closeTag(); ?>
    </div>    
</div>    

<script>
var div = document.getElementById('email-message');
document.getElementById("email").addEventListener("input", checkEmailValue);

function checkEmailValue(){
	var emailaddress = $("#email").val();
	if( !validateEmail(emailaddress)) {
		div.innerHTML = 'Email invalid! Use the basic format local-part@hostname.';
		div.style.display = 'block';
	}else{
		div.style.display = 'none';
	}
}

function validateEmail($email) {
	var emailReg = /^([\w-\.]+@([\w-]+\.)+[\w-]{2,4})?$/;
	return emailReg.test( $email );
}

</script>
